/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gantt;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author Mato
 */
public class Simulator extends javax.swing.JFrame {
    public Logic _func;
    int identif =0;
   
    public Simulator() {
        initComponents();
       _func = new Logic();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sjf_non_preem_button = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        button3 = new java.awt.Button();
        jTextField2 = new javax.swing.JTextField();
        sfj_preemp_button = new java.awt.Button();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        avgWaitingField = new javax.swing.JTextField();
        avgTurnaroundField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(119, 205, 255));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, -1));

        jTable2.setBackground(new java.awt.Color(119, 205, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Process", "Burst", "Arrival"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 290, 180));

        jTable3.setBackground(new java.awt.Color(119, 205, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Process", "Burst", "Arrival", "Wait", "Turn"
            }
        ));
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 270, 180));

        button1.setBackground(new java.awt.Color(249, 84, 84));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Insert to Table");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 110, 23));

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(119, 205, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 900, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 900, -1));

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 900, 1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Process Calculations");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Gantt Chart");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Scheduling Algorithm Simulator, Introduction to Operating Systems Project, Mateo Sheme");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Initial Values");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        sjf_non_preem_button.setBackground(new java.awt.Color(249, 84, 84));
        sjf_non_preem_button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        sjf_non_preem_button.setForeground(new java.awt.Color(255, 255, 255));
        sjf_non_preem_button.setLabel("SJF (Non-Preemptive)");
        sjf_non_preem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sjf_non_preem_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(sjf_non_preem_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, 50));

        jLabel8.setBackground(java.awt.Color.gray);
        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Enter Arrival times  and Burst times :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 270, 30));

        button3.setBackground(new java.awt.Color(249, 84, 84));
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setLabel("Clear Field");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 23));

        jTextField2.setBackground(new java.awt.Color(119, 205, 255));
        jTextField2.setOpaque(true);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, -1));

        sfj_preemp_button.setBackground(new java.awt.Color(249, 84, 84));
        sfj_preemp_button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        sfj_preemp_button.setForeground(new java.awt.Color(255, 255, 255));
        sfj_preemp_button.setLabel("SJF (Preemptive)");
        sfj_preemp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfj_preemp_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(sfj_preemp_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 50));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 70, 20));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 20, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Average Waiting Time :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Average Turnaround Time :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        avgWaitingField.setBackground(new java.awt.Color(119, 205, 255));
        avgWaitingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgWaitingFieldActionPerformed(evt);
            }
        });
        getContentPane().add(avgWaitingField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, -1));

        avgTurnaroundField.setBackground(new java.awt.Color(119, 205, 255));
        avgTurnaroundField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgTurnaroundFieldActionPerformed(evt);
            }
        });
        getContentPane().add(avgTurnaroundField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, -1));

        jPanel4.setBackground(new java.awt.Color(13, 146, 244));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try {
            _func.add_new(Integer.parseInt(jTextField1.getText()),Integer.parseInt(jTextField2.getText()));
            _func.show_data(jTable2);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField1.requestFocus();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for Burst Time and Arrival Time");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        _func = new Logic();
        for(int i = 0; i < 11; i++){
            jTable2.setValueAt("", i, 0);
            jTable2.setValueAt("", i, 1);
            jTable2.setValueAt("", i, 2);
            jTable3.setValueAt("", i, 0);
            jTable3.setValueAt("", i, 1);
            jTable3.setValueAt("", i, 2);
            jTable3.setValueAt("", i, 3);
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
          if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int burstTime = Integer.parseInt(jTextField1.getText());
                int arrivalTime = Integer.parseInt(jTextField2.getText());
                _func.add_new(burstTime, arrivalTime);
                _func.show_data(jTable2);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField1.requestFocus();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Please enter valid numbers for Burst Time and Arrival Time");
            }
          }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void sjf_non_preem_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sjf_non_preem_buttonActionPerformed
        jPanel2.removeAll();
        jPanel2.repaint();
        _func.computeSJFNonPreemptive(jTable3);
        _func.creationSJFNonPreemptive(jPanel2);
        double avgTurnaround = _func.calculateAvgTurnaroundTime(jTable3);
        double avgWaiting = _func.calculateAvgWaitingTime(jTable3);
        avgTurnaroundField.setText(String.format("%.2f", avgTurnaround));
        avgWaitingField.setText(String.format("%.2f", avgWaiting));
    }//GEN-LAST:event_sjf_non_preem_buttonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void sfj_preemp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfj_preemp_buttonActionPerformed
        jPanel2.removeAll();
        jPanel2.repaint();
        _func.compute_sjfpre(jTable3);
        _func.creationSJF(jPanel2);
        double avgTurnaround = _func.calculateAvgTurnaroundTime(jTable3);
        double avgWaiting = _func.calculateAvgWaitingTime(jTable3);
        avgTurnaroundField.setText(String.format("%.2f", avgTurnaround));
        avgWaitingField.setText(String.format("%.2f", avgWaiting));
       
    }//GEN-LAST:event_sfj_preemp_buttonActionPerformed

    private void avgTurnaroundFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgTurnaroundFieldActionPerformed

    }//GEN-LAST:event_avgTurnaroundFieldActionPerformed

    private void avgWaitingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgWaitingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgWaitingFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avgTurnaroundField;
    private javax.swing.JTextField avgWaitingField;
    private java.awt.Button button1;
    private java.awt.Button button3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Button sfj_preemp_button;
    private java.awt.Button sjf_non_preem_button;
    // End of variables declaration//GEN-END:variables
}
